### ISSUE TITLE
Add mirror-core

### ISSUE THREAD

**Issue by ejgallego** [coq-contribs/coq-contribs#1]
Please add mirror-core and its dependencies to coq-contribs:
- https://github.com/gmalecha/coq-plugin-utils
- https://github.com/coq-ext-lib/coq-ext-lib
- https://github.com/gmalecha/mirror-core

Thanks.

**Comment by ghost** [comment]
The common properties of all coq-contribs are documented [here](https://github.com/coq-contribs/coq-contribs/blob/master/FAQ.md#what-are-the-common-properties-of-all-coq-contribs).

Is there any hope that `mirror-core` can possibly conform to them?

(I haven't tried to explain the rules; in case if you think the motivation is unclear, please ask for more details)

**Comment by ejgallego** [comment]
I have moved to a different integration solution, so closing this; if anyone is interested in taking over please reopen.
