### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [coq-contribs/coq-contribs#3]
Any chance you could release the `.md` files in this repository under a [permissive license](http://choosealicense.com)?

You may have noticed that your repository is incorrectly detected as GCC Machine Description. I'm trying to fix the issue at [Linguist](https://github.com/github/linguist) and I'd like to use your `TODO.md` file as a sample.

Thanks!

**Comment by ghost** [comment]
For the time being, there are no such plans (to release these few files under some such license).

On the other hand, we wonder why would you need that in order to achieve what you are trying to do. Isn't the concept of [fair use](http://fairuse.stanford.edu/overview/fair-use/what-is-fair-use/) of the copyrighted work sufficient in this case?

**Comment by pchaigno** [comment]
I am not a lawyer myself, but we had confirmation from the GitHub legal team several times (for instance, see github/linguist#3137) that we should use permissive licenses for our samples. The important detail here might be that the samples are included with the code in each release.

**Comment by ghost** [comment]
Well, I am not aware of a concrete plan to change the licensing status of these (few) files.

It is a kind of internal information that, in the present form, can stay where it is.

**Comment by pchaigno** [comment]
Would it be feasible to publish this particular file as a Gist (or other) with a header stating the license?

**Comment by ejgallego** [comment]
Well the fact that the .md files have not a license it is a bug and basis to request the removal of this repository from github, so the OP has a point.

**Comment by ghost** [comment]
@pchaigno: From the two options:
- releasing `TODO.md`
- not releasing `TODO.md`

I prefer the second one. It enables me to keep all options open, including deleting all copies of that file once it is no longer necessary.

@ejgallego: Emilio, how did you concluded that?

**Comment by pchaigno** [comment]
@matej-kosik Thanks for your time.

**Comment by ejgallego** [comment]
@matej-kosik Oh I take it back sorry, I likely confused the GitHub TOS with some other service. However note that the TOS state:

> However, by setting your pages to be viewed publicly, you agree to allow others to view your Content. By setting your repositories to be viewed publicly, you agree to allow others to view and fork your repositories.

So this could lead to confusion, IMO having a license doesn't hurt.
